# Generated by Django 4.1 on 2023-10-28 10:22

from django.db import migrations, models

import apps.recruiters.models


class Migration(migrations.Migration):
    dependencies = [
        ("recruiters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiter",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.recruiters.models.recruiter_avatar_path,
            ),
        ),
    ]
