# Generated by Django 4.1 on 2023-10-26 14:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_education_started_at'),
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='favorite_students',
            field=models.ManyToManyField(to='students.student'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
