# Generated by Django 4.1 on 2023-10-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruiters", "0002_recruiter_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiter",
            name="company",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
