# Generated by Django 4.1 on 2023-10-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="telegram",
            field=models.URLField(blank=True, null=True),
        ),
    ]
