# Generated by Django 4.1 on 2023-10-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_alter_education_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentskill",
            name="score",
            field=models.IntegerField(
                choices=[
                    (1, "Beginner"),
                    (2, "Basic"),
                    (3, "Middle"),
                    (4, "Professional"),
                ],
                default=1,
            ),
        ),
    ]
